p/flask_app/courses/routes.py
from ssl import CertificateError
import base64,io
from io import BytesIO
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_required

from .. import course_client, club
from ..forms import AddClubForm, RemoveClubForm, SearchForm, AddCourseForm, RemoveCourseForm
from ..models import User, Review
from ..utils import current_time

courses = Blueprint("courses", __name__)

""" ************ View functions ************ """


@courses.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("courses.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)


@courses.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    # print(len(club.clubs)) # 950
    is_course = False
    try:
        if query in club.clubs:
            results = club.search(query)
        else:
            is_course = True
            results = course_client.search(query)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e))
    
    users = []
    if current_user.is_authenticated:
        users = User.objects(username = query)
        
    # return render_template("query.html", results=results, users = users)
    return render_template("query.html", results=results, users = users, course=is_course)


@courses.route("/courses/<course_name>", methods=["GET", "POST"])
def course_detail(course_name):
    try:
        result = course_client.retrieve_course_by_id(course_name)
        # return render_template("course_detail.html", course=result)
    except ValueError as e:
        return render_template("course_detail.html", error_msg=str(e))

    return render_template("course_detail.html", course=result, current_user = current_user)





@courses.route("/add_course/<course_name>", methods=["GET", "POST"])
@login_required
def add_course(course_name):
    form = AddCourseForm()
    course = course_name.strip()
    
    if form.validate_on_submit():
       
        type = form.select_field.data
        if type == "interested":
            if course not in current_user.interested_courses:
                current_user.interested_courses.append(course)
                flash(f"'{course}'  added to Interested Courses.")
            else:
                flash(f"'{course_name}' is already in your Interested Courses.", "error")
        elif type == "enrolled":
            if course not in current_user.enrolled_courses:
                current_user.enrolled_courses.append(course)
                flash(f"'{course}'  added to enrolled Courses.")
            else:
                flash(f"'{course_name}' is already in your Enrolled Courses.", "error")
        current_user.save()
        return redirect(url_for("courses.index"))
    return render_template("add_course.html", form=form, course_name=course, current_user = current_user)


@courses.route("/remove_course/<course_name>", methods=["GET", "POST"])
@login_required
def remove_course(course_name):
    form = RemoveCourseForm()  # Create the form instance
    course = course_name.strip()

    if form.validate_on_submit():  # Check if the form was submitted correctly
        

        # Check if course exists in user's lists
        if course_name in current_user.interested_courses:
            current_user.interested_courses.remove(course_name)
        elif course_name in current_user.enrolled_courses:
            current_user.enrolled_courses.remove(course_name)
        else:
            flash("Course not found in your list!", "error")
            return redirect(url_for("courses.index"))

        # Save changes to the database
        current_user.save()
        flash("Course removed successfully!", "success")
        return redirect(url_for("courses.index"))

    return render_template("remove_course.html", form=form, course_name=course)


@courses.route("/courses/club/<club_name>", methods=["GET", "POST"])
def club_detail(club_name):
    try:
        result = club.search(club_name)
        # return render_template("course_detail.html", course=result)
    except ValueError as e:
        return render_template("club_detail.html", error_msg=str(e))

    return render_template("club_detail.html", club=result, current_user = current_user)



@courses.route("/add_club/<club_name>", methods=["GET", "POST"])
@login_required
def add_club(club_name):
    form = AddClubForm()
    club = club_name

    if form.validate_on_submit():

        type = form.select_field.data
        if type == "interested":
            if club not in current_user.interested_clubs:
                current_user.interested_clubs.append(club)
                flash(f"'{club}'  added to Interested Clubs.")
            else:
                flash(f"'{club}' is already in your Interested Clubs.", "error")
        elif type == "enrolled":
            if club not in current_user.enrolled_clubs:
                current_user.enrolled_clubs.append(club)
                flash(f"'{club}'  added to enrolled club.")
            else:
                flash(f"'{club}' is already in your Enrolled Clubs.", "error")
        current_user.save()
        return redirect(url_for("courses.index"))
    return render_template("add_club.html", form=form, club_name=club, current_user = current_user)

@courses.route("/remove_club/<club_name>", methods=["GET", "POST"])
@login_required
def remove_club(club_name):
    form = RemoveClubForm()  # Create the form instance
    club = club_name

    if form.validate_on_submit():  # Check if the form was submitted correctly
        # Check if course exists in user's lists
        if club in current_user.interested_clubs:
            current_user.interested_clubs.remove(club)
        elif club in current_user.enrolled_clubs:
            current_user.enrolled_clubs.remove(club)
        else:
            flash("Club not found in your list!", "error")
            return redirect(url_for("courses.index"))

        # Save changes to the database
        current_user.save()
        flash("Club removed successfully!", "success")
        return redirect(url_for("courses.index"))

    return render_template("remove_club.html", form=form, club_name=club)

p/flask_app/users/routes.py
import base64,io
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm, FollowForm, UnfollowForm
from ..models import User

users = Blueprint("users", __name__)
""" ************ Helper for pictures uses username to get their profile picture************ """
def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

""" ************ User Management views ************ """


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('movies.index'))
    form = RegistrationForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_password)
            user.save()
            return redirect(url_for('users.login'))
    return render_template('register.html', form = form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('movies.index'))
    
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.objects(username = form.username.data).first()
            
            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.account'))
            else:
                flash("Login failed!", 'auth-fail')
    return render_template('login.html', form = form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect('/')


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            current_user.modify(username=update_username_form.username.data)
            current_user.save()

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            img = update_profile_pic_form.picture.data
            filename = secure_filename(img.filename)
            content_type = f'images/{filename[-3:]}'
            
            if current_user.profile_pic.get() is None:
                current_user.profile_pic.put(img.stream, content_type=content_type)
            else:
                current_user.profile_pic.replace(img.stream, content_type=content_type)
            current_user.save()
            return redirect(url_for('users.account'))
    profile_pic_bytes = BytesIO(current_user.profile_pic.read())
    profile_pic_base64 = base64.b64encode(profile_pic_bytes.getvalue()).decode()
    
    following_people = current_user.following_people
    potential_courses = current_user.potential_courses()
    potential_clubs = current_user.potential_clubs()
    
    return render_template(
        "account.html",
        update_username_form = update_username_form, 
        update_profile_pic_form = update_profile_pic_form, 
        profile_pic_base64 = profile_pic_base64, 
        following_people = following_people,
        potential_courses = potential_courses,
        potential_clubs = potential_clubs
        )


@users.route("/user/<username>", methods=["GET", "POST"])
@login_required
def user_detail(username):
    user = User.objects(username=username).first()
    
    if user is None:
        error_message = f"No user found"
        return render_template('user_detail.html', error=error_message)
    
    img = get_b64_img(user.username) 
    interested_courses = user.interested_courses
    enrolled_courses = user.enrolled_courses
    
    interested_clubs = user.interested_clubs
    enrolled_clubs = user.enrolled_clubs
    
    follow_form = FollowForm(prefix="follow")
    unfollow_form = UnfollowForm(prefix="unfollow")
    
    is_following = user in current_user.following_people

    if follow_form.submit_follow.data and follow_form.validate_on_submit():
        if not is_following:
            current_user.following_people.append(user)
            current_user.save()
            flash(f"You are now following {username}.", "success")
        return redirect(url_for("users.user_detail", username=username))

    if unfollow_form.submit_unfollow.data and unfollow_form.validate_on_submit():
        if is_following:
            current_user.following_people.remove(user)
            current_user.save()
            flash(f"You have unfollowed {username}.", "success")
        return redirect(url_for("users.user_detail", username=username))
    
    return render_template(
        'user_detail.html',
        image=img,
        follow_form=follow_form,
        unfollow_form=unfollow_form,
        follow=is_following, 
        interested_courses = interested_courses, 
        enrolled_courses = enrolled_courses, 
        interested_clubs = interested_clubs,
        enrolled_clubs = enrolled_clubs
    )

p/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if profile_pic_base64 %}
        {# Profile picture #}
        <img class="rounded-2xl h-24 w-24" src="data:image/png;base64,{{profile_pic_base64}}" alt="image">
    {% endif %}

    <h1 class="text-3xl text-neutral-950 dark:text-neutral-100 font-bold"> Welcome, {{current_user.username}}!</h1>

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        <h3 class="account_subheader">
            Update Username
        </h3>
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username(class="form-content", placeholder="Username") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        <h3 class="account_subheader">
            Update Profile Picture
        </h3>
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<!-- Users Interested and Enrolled courses -->
<div class="account-info">
    <h2 class="account_subheader">Interested Courses</h2>
    <ul>
        {% for course in current_user.interested_courses %}
        <li class="account-list">
            <a href="{{ url_for('courses.course_detail', course_name=course) }}"> &middot; {{ course }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Users Interested and Enrolled courses -->
<div class="account-info">
    <h2 class="account_subheader">Enrolled Courses</h2>
    <ul>
        {% for course in current_user.enrolled_courses %}
        <li class="account-list">
            <a href="{{ url_for('courses.course_detail', course_name=course) }}"> &middot; {{ course }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Users Interested and Enrolled club -->
<div class="account-info">
    <h2 class="account_subheader">Interested Clubs</h2>
    <ul>
        {% for club in current_user.interested_clubs %}
        <li class="account-list">
            <a href="{{ url_for('courses.club_detail', club_name=club) }}"> &middot; {{ club }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="account-info">
    <h2 class="account_subheader">Enrolled Clubs</h2>
    <ul>
        {% for club in current_user.enrolled_clubs %}
        <li class="account-list">
            <a href="{{ url_for('courses.club_detail', club_name=club) }}"> &middot; {{ club }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="account-info">
    <h2 class="account_subheader">Following</h2>
    <ul>
        {% for user in following_people %}
        <li class="account-list">
            <a href="{{ url_for('users.user_detail', username=user.username) }}"> &middot; {{user.username}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="account-info">
    <h2 class="account_subheader">People you follow are taking/interested in these courses (sorted by count)</h2>
    <ul>
        {% for course, _ in potential_courses %}
        <li class="account-list">
          <a href="{{ url_for('courses.course_detail', course_name=course) }}"> &middot; {{course}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="account-info">
    <h2 class="account_subheader">People you follow are taking/interested in these clubs (sorted by count)</h2>
    <ul>
        {% for club, _ in potential_clubs %}
        <li class="account-list">
          <a href="{{ url_for('courses.club_detail', club_name=club) }}"> &middot; {{club}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

p/flask_app/templates/add_club.html
{% extends "header.html" %}
{% block content %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        <h3 class="account_subheader mx-auto">
            {{ club_name }}
        </h3>
        {{ form.hidden_tag() }}
        <div class="form-group">
            <h1 class="account_subheader !font-normal !text-base">Current Status:</h1>
            {{ form.select_field(class="form-content") }}
        </div>
        {{ form.submit_add_club(class="review-button") }}
    </form>
</div>



{% endblock %}

p/flask_app/templates/add_course.html
{% extends "header.html" %}
{% block content %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        <h3 class="account_subheader mx-auto">
            {{ course_name }}
        </h3>
        {{ form.hidden_tag() }}
        <div class="form-group">
            <h1 class="account_subheader !font-normal !text-base">Current Status:</h1>
            {{ form.select_field(class="form-content") }}
        </div>
        {{ form.submit_add_course(class="review-button") }}
    </form>
</div>

{% endblock %}

p/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='output.css')}}"
    />
    <!-- href="{{url_for('static', filename='output.css')}}" -->
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Course Match</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

p/flask_app/templates/club_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

{% if club %}
<div class="course-container">
  <ul class="course-info">
    <div class="course-name"> 
      {{ club[0][0] }}
      <img src="data:image/jpeg;base64,{{ club[0][3] }}" width="100px">
    </div>

    {% if club[0][0] not in current_user.interested_clubs and club[0][0] not in current_user.enrolled_clubs %}
      <a class="navlink mx-auto" href="{{ url_for('courses.add_club', club_name=club[0][0]) }}">Add</a>
    {% else %}
      <a class="navlink mx-auto !bg-red-400/20 !text-red-400" href="{{ url_for('courses.remove_club', club_name=club[0][0]) }}">Remove</a>
    {% endif %}
    <!--
    <div class="course-title" style="margin-left: 40%;"> 
        <h1><b>{{ club[0][0] }}</b></h1>
        <img src="data:image/jpeg;base64,{{ club[0][3] }}" width="100px">
    </div>
  -->
    <li class="md:px-4"><b>Link: </b> <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{club[0][1]}}">{{ club[0][1] }}</a></li>
    <li class="md:px-4"><b>Description: </b> {{ club[0][2] }}</li>
    
  </ul>
</div>
{% endif %}

{% endblock %}

p/flask_app/templates/course_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

{% if course %}
<div class="course-container">
  <ul class="course-info">
    <div class="course-name"> 
      {{ course.name }}
      <p class="course-title"> &middot; {{ course.title }}</p>
    </div>

    {% if course.name not in current_user.interested_courses and course.name not in current_user.enrolled_courses %}
      <a class="navlink mx-auto" href="{{ url_for('courses.add_course', course_name=course.name) }}">Add</a>
    {% else %}
      <a class="navlink mx-auto !bg-red-400/20 !text-red-400" href="{{ url_for('courses.remove_course', course_name=course.name) }}">Remove</a>
    {% endif %}

    <li class="md:px-4"><b>Number of credits: </b> {{ course.credits }}</li>
    <li class="md:px-4">{{ course.description | safe}}</li>
  </ul>
</div>
{% endif %}

{% endblock %}

p/flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('courses.index') }}">
        <!-- <span class="hidden sm:block">Course Match</span> -->
        <span class="block">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 !text-red-400" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

p/flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <h2 class="main-title">Course Match</h2>
  <form class="searchbar" action="/" method="POST">
    {{ form.csrf_token }}
    {{ form.search_query(class="form-control", placeholder="Search a course, club, or person") }}

    {% if form.search_query.errors %}
      <div class="error" role="alert">
        {% for error in form.search_query.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
    
    {{ form.submit(class="form-button") }}
  </form>
</div>
{% endblock %}

p/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center text-neutral-950 dark:text-neutral-100">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2text-neutral-950 dark:text-neutral-100">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages(category_filter=['auth-fail']) %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}


    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

p/flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div class="results-container">

  {% if results|length > 0 %}
    {% for result in results %}
      {% if not course %}
        <a href="{{ url_for('courses.club_detail', club_name=result[0]) }}"
           class="group course-card">
          <h5 class="course-card-content"> {{ result[0] }}
            <img src="data:image/jpeg;base64,{{ result[3] }}" width="60px">
          </h5>
        </a>
      {% else %}
        {% if result.name %}
          <a href="{{ url_for('courses.course_detail', course_name=result.name) }}"
             class="group course-card">
            <h5 class="course-card-content"> {{ result.name }}
              <span class="text-neutral-600 dark:text-neutral-400 font-normal"> &middot; {{ result.title }} </span>
            </h5>
          </a>
        {% endif %}
      {% endif %}
    {% endfor %}
  {% endif %}

  {% if users|length > 0 %}
    {% for user in users %}
      <a href="{{ url_for('users.user_detail', username=user.username) }}"
         class="group course-card">
        <h5 class="course-card-content"> {{ user.username }}</h5>
      </a>
    {% endfor %}
  {% endif %}
</div>

{% endblock %}

p/flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center text-neutral-950 dark:text-neutral-100">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2 text-neutral-950 dark:text-neutral-100">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label(class="text-neutral-950 dark:text-neutral-100") }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}

p/flask_app/templates/remove_club.html
{% extends "header.html" %}
{% block content %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        <h3 class="account_subheader mx-auto">
            {{ club_name }}
        </h3>
        {{ form.hidden_tag() }}
        {{ form.submit_remove_club(class="review-button") }}
    </form>
</div>

{% endblock %}

p/flask_app/templates/remove_course.html
{% extends "header.html" %}
{% block content %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        <h3 class="account_subheader mx-auto">
            {{ course_name }}
        </h3>
        {{ form.hidden_tag() }}
        {{ form.submit_remove_course(class="review-button") }}
    </form>
</div>

{% endblock %}

p/flask_app/templates/user_detail.html
{% extends "header.html" %} {% block content %}

{% if error %}
    <b class="text-red-400" role="alert">
        {{ error }}
    </b>
{% endif %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# User's Profile Picture #}
    <img class="rounded-2xl" src="data:image/png;base64,{{image}}" alt="image">

    {% if follow %}
    <form method="POST">
        {{ unfollow_form.hidden_tag() }}
        {{ unfollow_form.submit_unfollow(class="navlink mx-auto !bg-red-400/20 !text-red-400") }}
    </form>
    {% else %}
        <form method="POST">
            {{ follow_form.hidden_tag() }}
            {{ follow_form.submit_follow(class="navlink mx-auto") }}
        </form>
    {% endif %}

</div>

<!-- Users Interested and Enrolled courses -->
<div class="account-info">
    <h2 class="account_subheader">Interested Courses</h2>
    <ul>
        {% for course in interested_courses %}
        <li class="account-list">
            <a href="{{ url_for('courses.course_detail', course_name=course) }}"> &middot; {{ course }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Users Interested and Enrolled courses -->
<div class="account-info">
    <h2 class="account_subheader">Enrolled Courses</h2>
    <ul>
        {% for course in enrolled_courses %}
        <li class="account-list">
            <a href="{{ url_for('courses.course_detail', course_name=course) }}"> &middot; {{ course }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Users Interested and Enrolled club -->
<div class="account-info">
    <h2 class="account_subheader">Interested Clubs</h2>
    <ul>
        {% for club in interested_clubs %}
        <li class="account-list">
            <a href="{{ url_for('courses.club_detail', club_name=club) }}"> &middot; {{ club }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="account-info">
    <h2 class="account_subheader">Enrolled Clubs</h2>
    <ul>
        {% for club in enrolled_clubs %}
        <li class="account-list">
            <a href="{{ url_for('courses.club_detail', club_name=club) }}"> &middot; {{ club }}</a>
        </li>
        {% endfor %}
    </ul>
</div>


{% endblock %}